### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#1296]
Load testing, to generate data in a test cluster and make load for testing functionality and performance.

The benefit of this will be to allow us to see how Headlamp performs under simulated load similar to what we are trying to achieve in production. Hopefully without having to spend a lot on cloud resources (or none) and not having to actually test in production.

- [x] How to do a load test for headlamp is documented. #1355
- [x] The limits and functionality to be load tested are documented. #1355
- [x] Scripts or instructions to make this easier (eg, generate logs, generate events) are available. #1355 and #1676
- [x] A report on the results of a load test is made. ( A number of new issues were made under https://github.com/headlamp-k8s/headlamp/labels/performance label )

This is part of the performance epic https://github.com/headlamp-k8s/headlamp/issues/1161

**Comment by illume** [comment]
https://kwok.sigs.k8s.io/ is one possibility for load testing headlamp on laptop (1000s of nodes).
