### ISSUE TITLE
Support advanced use-cases in our table

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1646]
We want to support use-cases where the MUI Table (that we use to implement our SimpleTable) falls short.

One option is to use e.g. [Material React Table](https://www.material-react-table.com/).
Maybe we also take the chance and instead of reimplementing SimpleTable, we leave it be and create a new component with a less deceiving name 🙂 Maybe just... Table.

Here are the things we need in this new table:
- [ ] Easy context menus (unblocks #1006 )
- [ ] Add column-based filtering (unblocks #1641 )
- [ ] Batch operations on items / rows selection + run action (unblocks #1640 )
