### ISSUE TITLE
[RFE] Add ability to port-forward to a pod directly from Headlamp

### ISSUE THREAD

**Issue by yolossn** [headlamp-k8s/headlamp#536]
It will be a nice addition to port-forward to an pod directly from the Headlamp UI. 
Refer:
https://github.com/kubernetes-client/javascript/blob/6c5a58f51b8cdb01c59cbd5b433013beb4940df2/examples/typescript/port-forward/port-forward.ts

**Comment by joaquimrocha** [comment]
Still a few things to care:
- [ ] Address all comments in #652 
- [ ] Add Port forwards section (into Network tab)
- [ ] Simplify backend if possible
